# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0333dc04c019db982718de25d44c02a5d9b8f6ea689d1ed12b07aceafce42a78f337c9cfeeacb66c309ff9cbac36f0598b0182f2b307961487e5eec236ce66f

test:
  secret_key_base: c6fd365624887f5eddf77571c71d89bc0f50c7956cba57cff33ccdc154822b3c541479a229b49167c6aa7606a30ba71a1090b1540a525ada94d745adb00f837e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
